name: GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: [3.9.17]
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls -r ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - run: echo "installing all requirements of the repo -- Quiz addition"
      # - name: Install dep
      #   run:  pip3 install --no-cache-dir -r requirements.txt
      # - name: Running test cases
      #   run: pytest
      # - name: Run python file
      #   run: python exp.py --hyperparameters hyperparameters.json
      - name: Build docker image
        run: |
          echo "Building docker image"
          docker build -t digits:v1 -f docker/Dockerfile .
      - name: Run docker image
        run: |
          echo "listing empty models directory"
          ls -lh models
          echo "Runnig docker image"
          docker run -v ./models:/digits/models digits:v1
          echo "listing models directory after image run"
          ls -lh models

